name: bson_codec
description: A BSDON codec for Dart.
version: 0.1.0
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/bson_codec

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  bson_objectid: ^0.1.0
  collection: ^1.9.1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
